# Site settings
title: René Klačan
email: rene.klacan@gmail.com
author: René Klačan
description: ""
baseurl:     ""
url:         "/"

# Google analytics
google_analytics: UA-56253737-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: reneklacan

# Social icons
show_social_icons: true
github_username: reneklacan
stackoverflow_id:
twitter_username: reneklacan
linkedin_username: reneklacan

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
gems:         [jekyll-paginate]
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
sass:
  ompressed: true
